#!/usr/bin/env sh

set -e

cd /var/www/html

if [[ -e /var/www/html/vendor/bin/heycart-deployment-helper ]]; then
    exec ./vendor/bin/heycart-deployment-helper run
fi

echo "### ERROR ###"
echo ""
echo "### The setup scripts are removed ###"
echo "### Please install the HeyCart Deployment Helper using composer require heycart/deployment-helper to continue ###"
echo "### For more information see https://developer.heycart.net/docs/guides/hosting/installation-updates/deployments/deployment-helper.html ###"
echo ""
echo "### ERROR ###"
echo ""

exit 1
